pipeline:
    name: MyBackendService
    identifier: MyBackendService
    projectIdentifier: dougproject
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: douglasjbothwellgithub
                repoName: myBackEndService
                build: <+input>
    stages:
        - stage:
              name: BuildBackEndService
              identifier: BuildBackEndService
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: docsgkedbothwellciquickstart
                          namespace: harness-delegate-ng
                          automountServiceAccountToken: true
                          nodeSelector: {}
                  execution:
                      steps:
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: pushToDockerHub
                                identifier: pushToDockerHub
                                spec:
                                    connectorRef: dbothwelldockerhub
                                    repo: dbothwell/mybackendservice
                                    tags:
                                        - latest
