pipeline:
    name: myBackEndService
    identifier: myBackEndService
    projectIdentifier: dougproject
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: douglasjbothwellgithub
                repoName: codebaseBeta
                build: <+input>
    stages:
        - stage:
              name: buildFrontEndService
              identifier: buildBackEndService
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: qadelegate
                          namespace: harness-delegate-ng
                          automountServiceAccountToken: true
                          nodeSelector: {}
                          os: Linux
                  execution:
                      steps:
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: pushToDockerRegistry
                                identifier: pushToDockerRegistry
                                spec:
                                    connectorRef: dbothwelldockerhub
                                    repo: dbothwell/mybackendservice
                                    tags:
                                        - mbe-latest
